name: Main workflow

on:
  push:
    branches:
      - main
      - develop
      - hotfix/*
      - "**" # Catch-all for other branches

jobs:
  load-and-print:
    name: Sample main workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout common repository
        uses: actions/checkout@v4
        with:
          repository: Redpill-Linpro-DK/marw-test-azure-deploy
          token: ${{ secrets.DIH_FAIR_COMMON_REPO_PAT }}
          path: common-repo

      - name: Load env
        uses: ./common-repo/.github/actions/loadEnvVariables
        with:
          rootDir: common-repo

      - name: Print Location Variable
        run: |
          echo "The location is: $resourceLocation"

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DIH_FAIR_AZURE_CREDENTIALS_DEV }}

      - name: Ensure Resource Group Exists and Deploy Resources
        run: |
          echo ">>> Using variable LOCATION: $resourceLocation"
          # Ensure the resource group exists
          az group create --name MARWTESTFROMGITHUB --location $resourceLocation

          # Deploy the resources using the common Bicep file
          az deployment group create \
            --resource-group MARWTESTFROMGITHUB \
            --template-file ./source/IaC/main.bicep

          # Deploy the resources using the local Bicep file
          az deployment group create \
            --resource-group MARWTESTFROMGITHUB \
            --template-file ./source/IaC/main.bicep
